# Generated by Django 5.2.10 on 2026-01-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshift',
            options={'verbose_name': 'Ca làm việc', 'verbose_name_plural': 'Ca làm việc'},
        ),
        migrations.AlterUniqueTogether(
            name='workshift',
            unique_together={('name', 'start_time', 'end_time')},
        ),
    ]
