# Generated by Django 5.2.10 on 2026-03-29 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

PGVECTOR_AVAILABLE = 'postgresql' in settings.DATABASES['default']['ENGINE']

if PGVECTOR_AVAILABLE:
    import pgvector.django.indexes
    import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                *(
                    [('embedding', pgvector.django.vector.VectorField(dimensions=512))]
                    if PGVECTOR_AVAILABLE
                    else [('embedding_json', models.TextField(default='[]'))]
                ),
                ('source', models.CharField(choices=[('original', 'Ảnh gốc'), ('augmented', 'Ảnh tăng cường'), ('registration', 'Đăng ký webcam')], default='original', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Embedding',
                'verbose_name_plural': 'Face Embeddings',
                **(
                    {
                        'indexes': [
                            pgvector.django.indexes.HnswIndex(
                                ef_construction=64,
                                fields=['embedding'],
                                m=16,
                                name='face_emb_hnsw_idx',
                                opclasses=['vector_cosine_ops'],
                            )
                        ]
                    }
                    if PGVECTOR_AVAILABLE
                    else {}
                ),
            },
        ),
    ]
