# Generated by Django 5.2.10 on 2026-05-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_faceembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='quality_score',
            field=models.FloatField(default=1.0, help_text='Độ rõ nét và chất lượng của khuôn mặt (0.0 - 1.0)'),
        ),
    ]
