# Generated by Django 5.2.10 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancelog_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='recognition_method',
            field=models.CharField(
                choices=[
                    ('legacy_unknown', 'Legacy/không rõ backend'),
                    ('facenet_inceptionresnet', 'FaceNet (InceptionResnetV1)'),
                    ('insightface_arcface', 'InsightFace ArcFace'),
                ],
                db_index=True,
                default='legacy_unknown',
                max_length=50,
            ),
        ),
    ]
